Register kafka producer as osgi service
stargate/producer-extensions pull request #6
Opened 2020-09-25 11:35 UTC by jorgebay

2020-09-25 11:36 UTC, jorgebay commented on kafka/pom.xml
> +    </dependency>
It will fail activating at runtime without this dependencies.

2020-09-25 11:44 UTC, tomekl007 requested changes

2020-09-25 11:44 UTC, tomekl007 commented on kafka/pom.xml
> +    </dependency>
The project does not compile right now because of:
```
producer-extensions/kafka/src/main/java/io/stargate/producer/kafka/producer/CompletableKafkaProducer.java:[9,17] package org.slf4j does not exist
```

2020-09-25 11:44 UTC, tomekl007 commented on kafka/pom.xml
> +              io.stargate.db,
I think it should be `io.stargate.producer`

2020-09-25 12:33 UTC, jorgebay commented on kafka/pom.xml
> +              io.stargate.db,
For this bundle to use the classes defined in `persistence-api`, we need to define it in `Import-Package`, otherwise when loading resolving it will fail to wire it.

2020-09-25 15:43 UTC, dougwettlaufer approved these changes

2020-09-28 08:58 UTC, tomekl007 commented
When I deployed this producer to the stargate, I was unable to see log:
`Registering Kafka producer...`
It only shows:
`Installing bundle producer-kafka-0.0.1-SNAPSHOT.jar`
there are also suspicious:
`Starting bundle null`

2020-09-28 09:10 UTC, jorgebay commented
The steps I use (order matters):

On stargate folder
```shell
% git status                                                                                   
On branch cdc-entities
Your branch is up to date with 'origin/cdc-entities'

% mvn clean install -DskipTests
```

On producer extension folder

```shell
% git status                                                                
On branch bundle-activator
Your branch is up to date with 'origin/bundle-activator'

% mvn clean package -DskipTests 

# Copy the resulting jar to the ./stargate-lib folder of stargate
% cp stargate-lib/producer-kafka-0.0.1-SNAPSHOT.jar ../stargate/stargate-lib
```

Back on stargate folder

```
# Verify producer jar is in there
% ls stargate-lib                                                                              
animal-sniffer-annotations-1.9.jar		cql-0.0.8-SNAPSHOT.jar				org.osgi.util.function-1.1.0.jar
asm-7.1.jar					health-checker-0.0.8-SNAPSHOT.jar		org.osgi.util.promise-1.1.1.jar
asm-analysis-7.1.jar				logback.xml					persistence-api-0.0.8-SNAPSHOT.jar
asm-tree-7.1.jar				org.apache.felix.scr-2.1.20.jar			persistence-cassandra-3.11-0.0.8-SNAPSHOT.jar
auth-api-0.0.8-SNAPSHOT.jar			org.apache.felix.scr.ds-annotations-1.2.10.jar	producer-kafka-0.0.1-SNAPSHOT.jar
auth-table-based-service-0.0.8-SNAPSHOT.jar	org.apache.felix.scr.generator-1.18.4.jar	restapi-0.0.8-SNAPSHOT.jar
authentication-0.0.8-SNAPSHOT.jar		org.osgi.compendium-4.2.0.jar			stargate-starter-0.0.8-SNAPSHOT.jar

% ./starctl --cluster-name stargate --cluster-version 3.11 --listen 127.0.0.10 --developer-mode

...
Starting bundle io.stargate.producer.kafka
INFO  [main] 2020-09-28 11:03:47,006 KafkaProducerActivator.java:32 - Registering Kafka producer...
```

2020-09-28 13:15 UTC, tomekl007 approved these changes

2020-09-28 13:16 UTC, tomekl007 requested changes

2020-09-28 13:16 UTC, tomekl007 commented on kafka/src/main/java/io/stargate/producer/kafka/KafkaProducerActivator.java
>   */
please make all methods synchornized

2020-09-28 13:17 UTC, tomekl007 commented
> Starting bundle io.stargate.producer.kafka
> INFO  [main] 2020-09-28 11:03:47,006 KafkaProducerActivator.java:32 - Registering Kafka producer...
> ```

it works for me now, thx!

2020-09-28 13:18 UTC, jorgebay commented on kafka/src/main/java/io/stargate/producer/kafka/KafkaProducerActivator.java
>   */
I think start is called once and the rest are there to adhere the interface, but are not used.

Do you still want us to have it synchronized?

2020-09-28 13:36 UTC, tomekl007 commented on kafka/src/main/java/io/stargate/producer/kafka/KafkaProducerActivator.java
>   */
I think that we should follow the same pattern as in `stargate/stargate`. In the future, it may change, and the `synchronize` will serve as a contract to the person that changes it. It will give info that we should be careful about thread-safety.

2020-09-28 14:15 UTC, dimas-b approved these changes
Changes LGTM, but CI seems to be failing :thinking:

2020-09-28 14:20 UTC, merged

2020-09-28 14:21 UTC, jorgebay commented
Test failures are related to not having updated snapshots published w/ CDC implementation, I've merged it to dev branch `kafka_cdc_producer`.